[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "toe"
version = "0.0.1"
description = "TN/QEC/QCA substrate scaffolding for ToE"
requires-python = ">=3.10"

[tool.setuptools]
packages = ["toe"]