name: ToE Continuous Integration

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-test-validate:
    name: Build, Test, and Validate Phase Outputs
    runs-on: ubuntu-latest
    env:
      MPLBACKEND: Agg
      OMP_NUM_THREADS: 1
      OPENBLAS_NUM_THREADS: 1
      MKL_NUM_THREADS: 1
      NUMEXPR_NUM_THREADS: 1
      PYTHONUNBUFFERED: "1"

    steps:
      # 1) Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      # 3) Dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest pandas matplotlib numpy scipy tensorly sympy

      # 4) Unit tests
      - name: Run Pytest suite
        run: pytest -q
        continue-on-error: false

      # 5) Core Phase 3 artifacts
      - name: Run validation examples
        run: |
          mkdir -p outputs/figs
          python examples/referee_pack.py
          python examples/lr_noise_sweep.py
          python examples/kl_tt_scan.py
          python examples/prediction_verifier.py > outputs/prediction_summary.json

      # 6) Phase 3.5 scans (optional but non-blocking if a script is absent)
      - name: Run Phase 3.5 extended scans
        run: |
          python examples/curvature_scan.py || true
          python examples/superfluid_mapping.py || true
          python examples/qca_continuum_bridge.py || true
          python examples/entropy_scaling_refit.py || true
          python examples/stochastic_stability_scan.py || true

      # (Optional) Phase 4 prototype, non-blocking
      - name: Run Phase 4 (gauge symmetry prototype)
        run: python examples/gauge_symmetry_scan.py || true

      # 7) Build LaTeX white paper
      - name: Build white paper (PDF)
        uses: xu-cheng/latex-action@v3
        with:
          root_file: white_paper_skeleton.tex
          working_directory: docs
          compiler: pdflatex

      # 8) Upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: phase3.5-artifacts
          path: |
            outputs/**/*.tsv
            outputs/**/*.png
            outputs/prediction_summary.json
            docs/white_paper_skeleton.pdf
          if-no-files-found: warn
