name: referee-pack

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  referee:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -e .
          # lightweight extras used by the referee pack
          pip install pandas matplotlib

      - name: Run unit tests (quick)
        run: |
          pytest -q

      - name: Run referee adversarial sweeps
        run: |
          python examples/referee_pack.py

      - name: Upload artifacts (plots + TSVs)
        uses: actions/upload-artifact@v4
        with:
          name: referee-artifacts
          path: |
            outputs/referee_*.tsv
            outputs/figs/referee_*.png
            docs/auto/referee_summary.tex
          if-no-files-found: warn
